apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sapawarga-webadmin
  namespace: sapawarga
spec:
  template:
    metadata:
      labels:
        app: sapawarga-webadmin
    spec:
      containers:
        - name: webadmin
          image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-webadmin:%VERSION%
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: sapawarga-webadmin-config-env
      imagePullSecrets:
        - name: regcred
