apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapawarga-webadmin
  namespace: sapawarga
  labels:
    app: sapawarga-webadmin
spec:
  selector:
    matchLabels:
      app: sapawarga-webadmin
  template:
    metadata:
      labels:
        app: sapawarga-webadmin
    spec:
      automountServiceAccountToken: false
      containers:
        - name: webadmin
          image: registry.gitlab.com/jdsteam/sapa-warga/sapawarga-webadmin:%VERSION%
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
      imagePullSecrets:
        - name: regcred
